gabesoft/evil-mc

- evil-mc-vars.el
Defining custom known commands in evil-mc-custom-known-commands didn't
make any effect because it was ignored by evil-mc-known-command-p.  Now
it is fixed.
> Allow custom commands in evil-mc-known-command-p

- evil-mc-vars.el
This is the second and final batch of evil-cleverparens. I believe I covered all of evil-cp's commands, if I have left any it shouldn't be hard to add them. There are still four commands that don't integrate with evil-mc, see details below.
These commands work, but don't appear in the code because they didn't require any handlers:
- `evil-cp-backward-up-sexp`
- `evil-cp-up-sexp`
- `evil-cp-backward-symbol-begin`
- `evil-cp-forward-symbol-end`
- `evil-cp-backward-sexp`
- `evil-cp-forward-sexp`
- `evil-cp-forward-symbol-begin`
- `evil-cp-previous-opening`
- `evil-cp-next-closing`
- `evil-cp-next-opening`
- `evil-cp-previous-closing`
- `evil-cp-beginning-of-defun`
- `evil-cp-end-of-defun`
- `evil-cp-backward-symbol-end`
- `evil-cp-toggle-balanced-yank`
- `evil-cp-yank-sexp`
- …
> Support more evil-cleverparens commands

- evil-mc-cursor-make.el
- evil-mc.el
Hi, this is a pull request and a proposal to add functions (and keybindings) to allow a user to create a new cursor at the current point and move the main cursor up (grk) or down (grj) in a single stroke. 
My motivation for this is to solve a common issue I have that is cumbersome to do otherwise with evil-mc. 
I frequently have a list of different words where I want to build a set of statements around each word. In order to get a cursor at the start of each of the words to edit them simulaneously, I have to pause cursors, make cursor at point, move down, for each word, then resume cursors at the last one. This results in a ton of key presses, especially with three key chords.
With this update a user would simply need to press 'grj' to make a cursor at the current point and move the main …
> add evil-mc functions to create cursor at point and move to next/previous line

- evil-mc-cursor-make.el
- evil-mc-vars.el
I more or less copied the changes in magnars multiple-cursors for this.
It introduces a function `evil-mc-cursor-is-bar` which is just copied from magnars mc.
Further it introduces a face `evil-mc-cursor-bar-face`, that uses the background color of evil-insert-state-cursor (this might be not optimal, but i guess most evil-mode users use the bar cursor for insert state).
the functions `evil-mc-cursor-overlay-at-eol` and `evil-mc-cursor-overlay-inline` are checking if the cursor is a bar and if so, they use the `evil-mc-cursor-bar-face`.
There is probably a better way to deside the background color of the new face (or without defining a new face) like your code does for the background color of the regular cursors, but my elisp knowledge is not that great, and this is working so far.
> Fake bar cursors

- evil-mc-scratch.el
insert-string is a obsolted function and removed from development Emacs(https://github.com/emacs-mirror/emacs/commit/949144c279e07e870ef4ee2de38787420b749828)
> Don't use obsoleted function

- evil-mc-known-commands.el
This will help spacemacs users to user evil-paste even when transient-paste state is enabled mentioned at #53 . This PR is paired with syl20bnr/spacemacs#8620
> Add spacemacs-evil/evil-mc-paste-* to known commands

- evil-mc-known-commands.el
As per request from syl20bnr/spacemacs#8620 the function names were renamed from
`spacemacs-evil/evil-mc-paste-*` to `spacemacs/evil-mc-paste-*`
> Renamed to `spacemacs/evil-mc-paste-*`

- evil-mc-known-commands.el
[tide](https://github.com/ananthakumaran/tide) is a TypeScript dev env in Emacs. It overrides `{`, `}`, `;`, etc in the insert mode and thus they doesn't work with extra cursors.
This is the information of `}` input in the insert mode.
```
} runs the command typescript-insert-and-indent, which is an interactive
compiled Lisp function in `typescript-mode.el'.
It is bound to ,, ;, :, ), (, }, {.
(typescript-insert-and-indent KEY)
Run the command bound to KEY, and indent if necessary.
Indentation does not take place if point is in a string or
comment.
```
Because of the `KEY`, maybe, I couldn't make it work with `:default`, and just used `self-insert-command` as we may not expect lines to be auto-indented when working with multiple cursors.
Please leave comments if there is a better way to …
> Add typescript-insert-and-indent to known commands

- README.org
- evil-mc-vars.el
- evil-mc.el
Currently the mode line text looks like this:
With the variables in this PR, the mode line can look like this:
This rewrites the mode line text assignment, with 4 variables:
```
evil-mc-one-cursor-show-mode-line-text
evil-mc-mode-line-text-paused
evil-mc-mode-line-text-inverse-colors
evil-mc-mode-line-text-cursor-color
```
**When there's only one cursor:**
text: show/hide "emc"
**When there are two or more cursors, resumed (unpaused):**
colors: cursor or default
**When there are two or more cursors, paused:**
text: show/hide "(paused)"
colors: inverse, cursor or default
**All 4 variables are enabled by default, resulting in:**
one cursor:
text: "emc" shown
two cursors, resumed:
color: cursor
two cursors, paused:
text: "(paused)" shown
colors: inverse
This also updates README.org, with a …
> Rewrite mode line text with 4 variables

- evil-mc-command-execute.el
- evil-mc-known-commands.el
There is an issue with "D" evil-paredit-delete-line: the editing cursor moves 1 char behind the others but if you move it "hl" it returns to normal. 
Everything else works.
> Add support for evil-paredit.

- README.org
- evil-mc-cursor-make.el
- evil-mc.el
- features/evil-mc-copy-paste.feature
This PR adds functionality of undoing the last added cursor, which is available in
other editors' multiple cursor implementations. This makes it possible to correct
the common mistake of creating too many cursors (e.g when hitting `C-n` past the
intended range), without having to start all over again.
Also changes the binding of "gru" to undo the very last added cursor instead
of deleting all cursors, in line with the meaning of "u = undo last action" in
evil mode.
The previous binding of `evil-mc-undo-all-cursors` is moved to "grq" ("quit")
> Add command to undo last added cursor

- evil-mc-known-commands.el
Right now on master if you enable outshine mode, the cloned cursors can't insert anything because outshine has it's own self-insert-command. This adds that command to the list of allowed commands.
Seems like someone at #22 was affected by this problem aswell.
> Added outshine insert support

- evil-mc-cursor-make.el
- evil-mc-known-commands.el
In evil/vi if you are in visual mode with a multi-line visual selection and press I or A, you are put into insert mode and when you exit, that insertion will be applied to every line in your visual selection.
This patch allows you to instead use multiple cursors to do this which allows for more advanced edits and somehow it seems to perform better than doing it the default way.
It seems like this was talked about in #43 and #22.
There is one minor bug I found that I can't bother solving right now however and that is if there is a tab where a cursor is supposed to be it will be put at the end of the tab. You would just need to make it break up the tab into spaces to fix this however.
> Make cursor on every line of visual selection

- evil-mc-cursor-make.el
Fixes: #101
Limited the commands:
`evil-mc-make-cursor-in-visual-selection-beg`
and
`evil-mc-make-cursor-in-visual-selection-end`
to only create cursors when there's an active selection.
> Limit cursor in visual selection beg/end commands

- evil-mc-setup.el
Fix an error on before-cursors-setup hook, which occurs when `whitespace-cleanup-disabled` is not defined.
```
Debugger entered--Lisp error: (void-variable whitespace-cleanup-disabled)
(boundp whitespace-cleanup-disabled)
(if (boundp whitespace-cleanup-disabled) (progn (setq whitespace-cleanup-disabled t) (setq evil-mc-custom-paused (cons (function (lambda nil (setq whitespace-cleanup-disabled nil))) evil-mc-custom-paused))))
evil-mc-before-cursors-setup-hook()
run-hooks(evil-mc-before-cursors-created)
evil-mc-cursors-before()
evil-mc-run-cursors-before()
evil-mc-make-cursor-move-by-line(1 nil)
evil-mc-make-cursor-move-next-line(nil)
funcall-interactively(evil-mc-make-cursor-move-next-line nil)
call-interactively(evil-mc-make-cursor-move-next-line nil nil) …
```
> Fix an error on before-cursors-setup hook

- evil-mc.el
It took me a while but this is round two of #100 
Given that I screwed up the first time I'd be nice if someone could confirm that this PR is ok.
I used https://github.com/noctuid/evil-guide#leader-key as the inspiration for the implementation. Maybe this can be rewritten more nicely? I'm still a bit confused about `evil-define-key` vs `define-key`. Also maybe I could use `define-prefix-command` instead of defvar for `evil-mc-cursors-map`?
@jojojames: the idea is that this is the first step in order to start modifying https://github.com/emacs-evil/evil-collection/issues/184. My goal is simply to then bind `evil-mc-cursors-map` to something appropriate and leave out the other invasive bindings (`C-n`, `M-p`, etc).
@duianto: thought you'd want to be noticed :smirk:
> Use a keymap

- features/support/env.el
cl is deprecated as of Emacs 27.
----
#
> Require cl-lib instead of cl

- evil-mc-cursor-make.el
In the emacs/native-comp branch, evil-mc-cursor-make.el fails to
compile, because:
Debugger entered--Lisp error: (user-error "Unknown interactive code: ‘<c>’")
user-error("Unknown interactive code: `%s'" "<c>")
evil-interactive-string("<c>")
evil-interactive-form("<c>")
apply(evil-interactive-form "<c>")
This PR fixes this error.
> Fix unknown interactive code problem

- evil-mc-cursor-state.el
- Add \`' quotes to `temporary-goal-column` fixing two checkdoc errors.
- `defvar`-declare `evil-mc-cursor-variables`.
----
#
> evil-mc-cursor-state.el: Fix warnings

- evil-mc-known-commands.el
Hi, the function `capitalize-word` is already part of `evil-mc-known-commands`. Therefore I think it makes sense to add `upcase-word` and `downcase-word` as well.
> Add upcase-word and downcase-word to known commands

- evil-mc-known-commands.el
Add support for several evil-org-mode functions by adding them to the variable ```evil-mc-known-commands```.
> more evil-org support hlissner/doom-emacs#4484

- evil-mc-command-record.el
in addition to pre and post types evil recently introduced pre-read-key-sequence
https://github.com/emacs-evil/evil/commit/2b2ba3cbeabe1f239b6b0ebdaddcb68dd158bd1f
fix #131
> evil-mc-command-record can handle new pre-read-key-sequence type, fix #131

- evil-mc-command-execute.el
- evil-mc-command-record.el
- evil-mc-common.el
- evil-mc-cursor-make.el
- evil-mc-cursor-state.el
- evil-mc-known-commands.el
- evil-mc-region.el
- evil-mc-scratch.el
- evil-mc-setup.el
- evil-mc-undo.el
- evil-mc-vars.el
- evil-mc.el
This PR enables lexical binding in this package and fixes the bugs that arose when doing so. This is important because in the future, lexical binding may become the default for Emacs so this prevents problems from arising in the future.
> enable lexical binding
